spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mazad?useUnicode=true&characterEncoding=utf8&useSSL=false
    name:
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 10
      pool-name: mazad_pool
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  sleuth.sampler.percentage: 1.0

flyway:
  enabled: false
  baseline-on-migrate: true
  baseline-version: 0
  encoding: UTF-8
  validate-on-migrate: false
  locations: classpath:db/dev/migration

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:7777/uaa/user/current
    client:
      clientId: mazad-service
      clientSecret: mazad-service-secret
      accessTokenUri: http://localhost:7777/auth/oauth/token
      userAuthorizationUri: http://localhost:7777/auth/oauth/authorize
      grant-type: client_credentials
      scope: server

server:
  port: 8181

logging:
  level:
    org:
      hibernate.SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
#      springframework.cloud.sleuth: DEBUG

# ===================================================================

mazad:
  feign:
    auth : http://localhost:7777/auth/
    service: http://localhost:8181/ws

  photo:
    path: /Users/technetmedia_khaled/projets/agendastorage
    url: http://192.168.1.2/agendastorage