spring:
  application:
    name: Mazad_Service_prod
  datasource:
    url: jdbc:mysql://localhost:3306/mazad?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: mazaduser
    password: 2fYY6xAt
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  sleuth.sampler.percentage: 0.5

flyway:
  baseline-on-migrate: true
  baseline-version: 0
  encoding: UTF-8
  validate-on-migrate: false
  locations: classpath:db/prod/migration

security:
  oauth2:
    resource:
      userInfoUri: http://localhost:7777/auth/user/current
    client:
      clientId: mazad-service
      clientSecret: mazad-service-secret
      accessTokenUri: http://localhost:7777/auth/oauth/token
      userAuthorizationUri: http://localhost:7777/auth/oauth/authorize
      grant-type: client_credentials
      scope: server

server:
    port: 8181
hystrix:
  threadpool.default:
    coreSize: 20
    maxQueueSize: 500000
    keepAliveTimeMinutes: 2
    queueSizeRejectionThreshold: 500000
  command.default:
    fallback.isolation.semaphore.maxConcurrentRequests: 20
    execution:
      timeout.enabled: false
      isolation:
        strategy: THREAD
        thread.timeoutInMilliseconds: 60000

logging:
  level:
    org:
      hibernate.SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE
# ===================================================================
mazad:
    feign:
      auth : http://localhost:7777/auth/
      service: http://localhost:8181/ws
    avatar:
      path: /home/ubuntu/workspace/mazadstorage/
      url: http://52.59.70.73/mazadstorage
    swagger:
      token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX25hbWUiOiJhZG1pbkBtYXphZC5jb20iLCJhdXRob3JpdGllcyI6WyJST0xFX0FETUlOIl0sImp0aSI6IjIwNGI1ZmQxLTU2N2QtNDEyOC1hZWZmLWI0YTkwZGIyYmFmMCIsImNsaWVudF9pZCI6Im1hemFkIiwic2NvcGUiOlsicmVhZCIsIndyaXRlIl19.PexCWeakSqz8_nQAoBYYQ8eHajkWJd4zhVILqkPFz3jhZ4HrcDnKlLWKi_Q95ERIQcohG1-JMyYD0EMC572M-IfLxTVI_RMVTeOzAxsafZzFUd9-GRRs0HpFDmLVALKwVeKtZgX4BPKBxuMOyF9AATlMAduq8dKN-D8s1SqknLCOzz68z4vD9wxRwhNoVFrVE48pTe6KRJMvr-v1JSFTnGbyLifXhEkFHvQqxQD6BCG8Lt4DZ7TVHxq_hPZg5AFIqqG0ipA9_LBWs9LKRqwLI3Q65TKoKlcHcBnEYGYvFKPom1MVeExUK-oo33X0AIIQDDIEGffAwSxXJGgHZKhzng